### ISSUE TITLE
Version 1.2.0 fails to install

### ISSUE THREAD

**Issue by ancodeUDW** [bbondy/bloom-filter-cpp#7]
I was using until yesterday bloom-filter-cpp the version 1.1.8, and it worked properly. however since yesterday afternoon, and keeping it today, when doing npm install it updates to the 1.2.0 and then it fails to compile. My operative system is Ubuntu 16.04.4 LTS.

After forcing to install the old version with npm --save install bloom-filter-cpp@1.1.8 it compiles properly. However, in my project I am using brave's ad-block, and it always try to install the latest version, so it fails and the module can't be install, regardless of me having installed bloom-filter-cpp v 1.1.8 before.

here I leave the error message

> ad-block@4.1.1 preinstall /git/addaps_desktop_electron_0.5/node_modules/ad-block
> > npm install bloom-filter-cpp && npm install hashset-cpp
> 
> npm WARN invalid config loglevel="notice"
> 
> > bloom-filter-cpp@1.2.0 install /git/addaps_desktop_electron_0.5/node_modules/ad-block/node_modules/bloom-filter-cpp
> > node-gyp rebuild
> 
> make: se entra en el directorio '/git/addaps_desktop_electron_0.5/node_modules/ad-block/node_modules/bloom-filter-cpp/build'
>   CXX(target) Release/obj.target/bloom-filter-cpp/addon.o
>   CXX(target) Release/obj.target/bloom-filter-cpp/BloomFilterWrap.o
> ../BloomFilterWrap.cpp: In static member function 'static void BloomFilterWrap::BloomFilterWrap::Add(const v8::FunctionCallbackInfo<v8::Value>&)':
> ../BloomFilterWrap.cpp:72:53: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Isolate*&, v8::Local<v8::String>)'
>    String::Utf8Value str(isolate, args[0]->ToString());
>                                                      ^
> In file included from /home/developer/.node-gyp/8.9.3/include/node/node.h:63:0,
>                  from ../BloomFilterWrap.h:9,
>                  from ../BloomFilterWrap.cpp:6:
> /home/developer/.node-gyp/8.9.3/include/node/v8.h:2764:14: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)
>      explicit Utf8Value(Local<v8::Value> obj);
>               ^
> /home/developer/.node-gyp/8.9.3/include/node/v8.h:2764:14: note:   candidate expects 1 argument, 2 provided
> ../BloomFilterWrap.cpp: In static member function 'static void BloomFilterWrap::BloomFilterWrap::Exists(const v8::FunctionCallbackInfo<v8::Value>&)':
> ../BloomFilterWrap.cpp:81:53: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Isolate*&, v8::Local<v8::String>)'
>    String::Utf8Value str(isolate, args[0]->ToString());
>                                                      ^
> In file included from /home/developer/.node-gyp/8.9.3/include/node/node.h:63:0,
>                  from ../BloomFilterWrap.h:9,
>                  from ../BloomFilterWrap.cpp:6:
> /home/developer/.node-gyp/8.9.3/include/node/v8.h:2764:14: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)
>      explicit Utf8Value(Local<v8::Value> obj);
>               ^
> /home/developer/.node-gyp/8.9.3/include/node/v8.h:2764:14: note:   candidate expects 1 argument, 2 provided
> bloom-filter-cpp.target.mk100 fallo en las instrucciones para el objetivo 'Release/obj.target/bloom-filter-cpp/BloomFilterWrap.o'
> make: *** [Release/obj.target/bloom-filter-cpp/BloomFilterWrap.o] Error 1
> make: se sale del directorio '/git/addaps_desktop_electron_0.5/node_modules/ad-block/node_modules/bloom-filter-cpp/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/git/addaps_desktop_electron_0.5/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 4.14.0-041400-lowlatency
> gyp ERR! command "/home/developer/.nvm/versions/node/v8.9.3/bin/node" "/git/addaps_desktop_electron_0.5/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /git/addaps_desktop_electron_0.5/node_modules/ad-block/node_modules/bloom-filter-cpp
> gyp ERR! node -v v8.9.3
> gyp ERR! node-gyp -v v3.6.0
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bloom-filter-cpp@1.2.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bloom-filter-cpp@1.2.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/developer/.npm/_logs/2018-06-28T06_58_32_623Z-debug.log
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ad-block@4.1.1 preinstall: `npm install bloom-filter-cpp && npm install hashset-cpp`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the ad-block@4.1.1 preinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/developer/.npm/_logs/2018-06-28T06_58_34_831Z-debug.log
>

**Comment by pfrazee** [comment]
We're seeing this on MacOS as well:

```
3.sdk/System/Library/Frameworks (framework directory)
End of search list.
../BloomFilterWrap.cpp:72:21: error: no matching constructor for initialization of
      'String::Utf8Value'
  String::Utf8Value str(isolate, args[0]->ToString());
                    ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/iradchenko/.node-gyp/iojs-2.0.2/deps/v8/include/v8.h:2764:14: note: candidate
      constructor not viable: requires single argument 'obj', but 2 arguments were provided
    explicit Utf8Value(Local<v8::Value> obj);
             ^
/Users/iradchenko/.node-gyp/iojs-2.0.2/deps/v8/include/v8.h:2771:5: note: candidate constructor
      not viable: requires 1 argument, but 2 were provided
    Utf8Value(const Utf8Value&) = delete;
    ^
../BloomFilterWrap.cpp:81:21: error: no matching constructor for initialization of
      'String::Utf8Value'
  String::Utf8Value str(isolate, args[0]->ToString());
                    ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/iradchenko/.node-gyp/iojs-2.0.2/deps/v8/include/v8.h:2764:14: note: candidate
      constructor not viable: requires single argument 'obj', but 2 arguments were provided
    explicit Utf8Value(Local<v8::Value> obj);
             ^
/Users/iradchenko/.node-gyp/iojs-2.0.2/deps/v8/include/v8.h:2771:5: note: candidate constructor
      not viable: requires 1 argument, but 2 were provided
    Utf8Value(const Utf8Value&) = delete;
    ^
2 errors generated.
make: *** [Release/obj.target/bloom-filter-cpp/BloomFilterWrap.o] Error 1
``

Same lines, 72 and 81.

**Comment by sc3w** [comment]
I got the same error on Mac. Did you found any solution to this?

**Comment by ancodeUDW** [comment]
> I got the same error on Mac. Did you found any solution to this?

My problem was with another module that uses this one as dependency. As how I fixed my problem, I did a fork of that module, and I forced it to download an earlier version of Bloom-filter-cpp. More specifically, In my fork I use bloom-filter-cpp 1.1.8 and hashset-cpp 2.0.1 <- both modules gave me the same problem.

`npm install bloom-filter-cpp@1.1.8 && npm install hashset-cpp@2.0.1`
